// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (id, creates_at, updated_at, username)
VALUES
    ($1, NOW (), NOW (), $2)
RETURNING id, creates_at, updated_at, username
`

type CreateUserParams struct {
	ID       uuid.UUID
	Username string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatesAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}
